### PR TITLE
Enables automatic dpi scaling.

### PR DESCRIPTION
**Pull request by sphh**
I have a high dpi scaling and the nodes in the main window were just tiny. According to https://doc.qt.io/qt-5/highdpi.html:

> The QT_ENABLE_HIGHDPI_SCALING environment variable, introduced in Qt 5.14, enables automatic scaling based on the pixel density of the monitor. Replaces QT_AUTO_SCREEN_SCALE_FACTOR.

This is the approach used in this PR.

Alternatives:

> The Qt::AA_EnableHighDpiScaling application attribute, introduced in Qt 5.6, enables automatic scaling based on the monitor's pixel density.

### CODE REVIEW

**Review by leon-thomm — APPROVED** [review]

**Comment by leon-thomm** [comment]
looking good, I will test later and then merge. please merge to dev branch instead, the main branch should contain releases only

**Comment by leon-thomm** [comment]
edit: actually thats not necessary, you can leave it as it is

**Comment by sphh** [comment]
Oh, so sorry for the main/dev confusion. That makes absolutely sense!

**Comment by sphh** [comment]
Thanks!

**Pull request merged**
